### ISSUE TITLE
Ask: keyboard app

### ISSUE THREAD

**Issue by DrSensor** [onlurking/termux#5]
Hi, sorry for asking this. What keyboard do you use in that screenshot? (README.md)

**Comment by becauseimnoob** [comment]
> Hi, sorry for asking this. What keyboard do you use in that screenshot? (README.md)

Since there has been no answer for 3 months this is top secret information.  @onlurking

**Comment by DrSensor** [comment]
Gotcha!
It's [Hacker's Keyboard](https://github.com/klausw/hackerskeyboard) with special settings.
![20230930_151940](https://github.com/onlurking/termux/assets/4953069/44ec4549-9bd7-4582-b32f-720f6b475de9)
